### ISSUE TITLE
provided testbed loading error

### ISSUE THREAD

**Issue by th0rgall** [p-en-o-cw-2016/testbed-provided#12] opened 2017-04-25 16:50 UTC
Initiating the provided testbed with the .wdf file generated with simple_example_world_description_file_builder.html creates two testbeds, one empty and one who disconnects a non-existing drone when the simulation is started. A new drone cannot be initialized via the wire after this. When no world file is loaded into the testbed, a drone can be initialized via wire. Tested on the lab computers.

**Comment by samldd** [comment] 2017-04-25 17:59
Was this also an issue on a previous version of the testbed?

**Comment by AntoonDeCleen** [comment] 2017-04-26 08:04
We only tested this version

**Comment by samldd** [comment] 2017-04-26 08:21
Can you please download the testbed again and look very good if it is V0.0.5. Cause I'm not able to reproduce this issue and it should have been resolved in an earlier release

**Comment by AntoonDeCleen** [comment] 2017-04-26 09:03
We downloaded it by the link provided in the announcement on toledo, which was indeed v0.0.1, apologies. The new version will be tested shortly.

**Comment by AntoonDeCleen** [comment] 2017-04-26 09:58
Updating to the newest version did indeed resolve this problem.

**Closed as completed** 2017-04-26 13:23 UTC
